### PR TITLE
Issue 125 - Multiple windows opening

### LINKED ISSUE #125: Multiple windows opening
This has only started happening since updating to the most recent version.

In proworkflow when I click a file link it now opens up in Microsoft Explorer three times instead of just the once.

Has there been a change to how the file paths should be done?

### PR DESCRIPTION
**Pull request by AWolf81**
## Changes
- Save `injectedTabs` object `{tabID1: true, tabID2: true}` in `browser.storage.local` with key `injectedTabs`
- Modified check from `indexOf` to object-based
- Add update of local storage at every change of `injectedTabs`
- Update `web-ext` extension (without this `npm start` had an issue - the extension could not be installed with newer FF version.)

## Tests
- [x] Open multiple tabs with file links, reload one tab and switch between tabs. Test if there are multiple Windows for folders or files after each switch. --> No multiple instances detected.
- [x] Dynamic link handling - every case of `http://localhost:3000/issue1/issue.htm` working. No multiple windows. Link handling OK.
- [x] Settings unaffected? Tested whitelist setting. Works. Just removing a URL requires a page reload - this could be improved later. 
- [x] Trello test - Link click works, reveal not working (opens editing mode) - same behavior as the previous version. --> OK
- [x] Test normal link + file link click (see http://localhost:3000/issue113/index.html)

## Fixes
#125 

@maxm199 would be great if you could test the branch if this is working as expected.

### CODE REVIEW

**Comment by maxm199** [comment]
Tried several times with multiple windows and never had the issue.
Seems to be fine, nice job!

**Comment by AWolf81** [comment]
@maxm199 great, thanks for testing.
I'll merge this today or tomorrow.

**Comment by maxm199** [comment]
I can't see any issue.
Unfortunately I won't be able to test it until tomorrow if you need it.
Have a nice day.

**Comment by maxm199** [comment]
Just checked from remote.
I can confirm that the version I tested 3 days ago had that issue, with the back button on click it opened 2/3 windows.
With the last changes it opens just 1 window on back/forward button, nice catch!

**Comment by AWolf81** [comment]
OK, thanks for testing and your confirmation.
Good to hear that this is working.

**Pull request merged**
