### PR TITLE
Migration webextension

### PR DESCRIPTION
**Pull request by AWolf81**
@feinstaub Can you please test the extension?
After merging I'd like to check if the download links are working in `installed.html`. At the moment, The links are not working because the files are not in master branch.

Do you think the installation for Linux is OK? I don't have an installer ready. I packaged everything into one file and it needs to be extracted to any location at the user's pc. After unpacking the installation needs to be started by executing `$ bash ./install_host.sh`. Python needs to be installed on user's machine.
Not sure why I required `bash` at the installation script but with-out that, it wasn't working.

Windows installation is easier here because the Python interpreter is bundled in the executable and the installer is doing the installation. I'm just not sure if the Visual studio redistributable should be installed by default - required for Py2Exe to work. (VS C++ redis. would require admin rights - that's why I disabled it by default).

Folder structure for the native host application is modified as discussed in the issue.

The following points are still open:
- Development read-me needs an update (web-ext)
- Gitignore requires an update (remove web-artifacts) - I'll add this after merging
- Some code cleaning required (remove commented code lines e.g. in background/index.js)
- No unit tests (Javascript + Python) - everything manually tested with Ubuntu & Windows
- Links with accents can't be opened (Unicode issue with Python 2.7 Popen)
- Context menu not implemented
- In browser open option not implemented
- Settings not immediately applied (reloading of tabs required)
- Executable prevention not perfect (I think .msi files at Windows can be still opened, couldn't test Linux here)

What do you think? Is it ready for the first release as web extension?

### CODE REVIEW

**Comment by feinstaub** [comment]
> After unpacking the installation needs to be started by executing $ bash ./install_host.sh. Python needs to be installed on user's machine.
> Not sure why I required bash at the installation script but with-out that, it wasn't working.

What exactly was "not working"? I did `$ ./install_host.sh` and got "Native messaging host webextension_local_filesystem_links has been installed." and $HOME/.mozilla/native-messaging-hosts/webextension_local_filesystem_links.json was created.

**Comment by feinstaub** [comment]
I noticed that the folder web-ext-artifacts has 14 MB. I would find it better if this is not part of the repository history of master.

I also saw that the Windows version and setup for native host is 20 MB large. In this case I would find it better if this was located elsewhere.

**Comment by feinstaub** [comment]
From README.dev.md I did:

$ npm install

Worked fine. Please note the following: "npm notice created a lockfile as package-lock.json. You should commit this file." --> We should commit this file.

$ npm run dev:FF

npm ERR! missing script: dev:FF

Should this work?

$ npm run-script build  # I guessed this one. The proper command should be part of the README.dev.txt

--> dist was created.

$ npm start

Firefox opens with moz-extension://a4d64394-06a3-4bd1-ba2f-0a9d6774dec5/installed.html

I think, that new "Thank your for installing" page is great. Thanks! Tool button in the toolbar is working.

"Linux (Python 2.7 dependency required)" --> We should go for Python 3 and not support Python 2.7 anymore.

"Test the addon at your pages or at this Jsfiddle." -> good to have this jsfiddle link

I tried the JSfiddle and it took some time until the icons appear. Is this normal? Ah, I have to go to Toolbar -> Localfilesystemlinks Icon -> Change Settings... and then go back, then the icons appear.

I tested with:

`<a href="file:///C:">C folder (tripple slashes - file:///c:)</a><br/>`

--> Error KIO client: "Unable to run the command specified. The file or folder does not exist." That means at least the Linux OS got some commands.

```
<a href="file:////home/gregor/tmp/tmp">home</a><br/>
<a href="file:///home/gregor/tmp/tmp">home 2</a><br/>
```

--> for both a firefox popup: "An unexpected error occurred. Please check that you have the native application installed"

`<a href="file://home/gregor/tmp/tmp">home 3</a><br/>`

--> Error KIO client: "The file or folder smb://home/gregor/tmp does not exist."

**Comment by AWolf81** [comment]
**Installation ./install.sh**
I don't remeber exactly the wording but something like `couldn't substitute...` script error. I can send the exact message later today.

`npm run dev:FF` can be removed because I've changed that to only run Firefox develpoment by default. I'll fix that.

**Bundle sizes**
`web-artifacts` will be added to gitignore as it's the build that will be hosted in Mozilla store. It should be smaller later because I've removed the host apps from that bundle.

Yes, no problem. We could add the installer files to Google drive for downloading. I would put both "binaries" (Windows / Linux) to another download location. So we will only have the source code in the repository. 
What about versioning the native apps? Should we add the same version as the extension or should we have a different version? I've started with version 0.0.1 just to have some version.

OK, I'll check if it's difficult to change to Python 3. Need to check if Py2Exe is also available for Python3 but I think I've seen that before.

**JS fiddle loading**
Yes, I've also noticed that it takes pretty long to load the fiddle. It takes probably around 2-4 seconds to show the icon (not measured yet). It will also show the icon if you're staying on the page. Maybe I'll check this later.

At the jsfiddle, there is also a problem with iframe reloading if you're clicking on run button in the fiddle. The icons won't be displayed. I've created a test page in the test/webserver but I'm not sure how to fix.

**Tests to home location**
4 and 3 slashes should work. I'll re-check this later.
The last with the two slashes won't work as there is one slash missing but I'll also check this. Is this a test case in the test/webserver?

The message with `check if native host is installed` should be improved but I haven't found a way to check the exact cause of the error. I'm just getting `unexpected error` with-out additional info. If the app is not installed I'm getting something like `couldn't post to disconnected port` in the developer console. But it's not that clear in the `onError` callback.

**Comment by AWolf81** [comment]
I'd like to keep Python 2.7 for the first release because I think it's not that easy to change to Python 3. I would also prefer Python 3 but it would probably take too much time.
(Py2Exe is not working & input streams are handled differently)
I've tried the code from [ping pong native messaging example](https://github.com/mdn/webextensions-examples/tree/master/native-messaging) but it wasn't working for me, not sure what's wrong and I'll try it again later.

I also would like to check if it's possible to create the native script in Nodejs because it's really easy to create an executable for Win, Linux & MacOS - I haven't tested this yet but it looks great at the following [blog post](https://dev.to/anaptfox/build-a-cross-platform-command-line-executable-innodejs).

Next I need to check the points you mentioned with opening the 3 or 4 slashes in Linux.

After that I'd like to do some code cleaning and if you're OK with this I'll merge the PR to master. (Before merging I'll also remove the bin folders and put theses files on google drive - to remove the large binaries from the repo.)

**Comment by AWolf81** [comment]
I've re-tested the installation with `./install_host.sh` and I'm getting the following error message:
`./install_host.sh: 36: ./install_host.sh: Bad substitution`

But `bash ./install_host.sh` is working.

Three & four slashes in links are working for me. Not sure what's wrong here in your OS. What OS do you use? Maybe I can do a setup and check it in a virtual machine.

The two slashes link was not working and I think it's not supported and shouldn't be. At my Ubuntu installation it removed the home part of the url and showed "could not open ...".

Tested with this [jsfiddle](https://jsfiddle.net/vwn3Lnzk/).

I've uploaded the "binaries" to Google drive and updated the links in the installation page. Also the bin folder is added to gitignore and removed from the repository.

What do you think? Can I merge the branch to master or is anything open?

**Comment by feinstaub** [comment]
> I'd like to keep Python 2.7 for the first release because I think it's not that easy to change to Python 3. I would also prefer Python 3 but it would probably take too much time.

Ok. Would you open an issue for that ("Use Python 3").

> I also would like to check if it's possible to create the native script in Nodejs because it's really easy to create an executable for Win, Linux & MacOS - I haven't tested this yet but it looks great at the following blog post.

Sounds good.

> Not sure what's wrong here in your OS. What OS do you use? Maybe I can do a setup and check it in a virtual machine.

openSUSE Tumbleweed 64 Bit with Plasma.

> I've uploaded the "binaries" to Google drive and updated the links in the installation page. 

I would prefer github-hosted binaries, but this can be done later.

> What do you think? Can I merge the branch to master or is anything open that I have to fix before merging?
> ...
> Also the bin folder is added to gitignore and removed from the repository.
> ...
> (Before merging I'll also remove the bin folders and put theses files on google drive - to remove the large binaries from the repo.)

Please confirm that these binaries will NOT show up in the master branch history. With a normal merge this cannot be accomplished. You either have to do an interactive rebase or drop all the branches history (which I would not mind as long as the history is clean). With this in mind, please merge.

> How to change the extension id to a more readable one (to improve issue #86)?

This can wait a bit, I think.

> Do we have to update the min version in package.json (see engines prop)?

I don't know. It should be increased to the point where Firefox starts to support WebExtension. If in doubt just keep it, the Addon site will probably send a notification.

> Is a min version in manifest.json requried? See docs here

I don't know. Let's try without (or check the latest addon tutorial if it shows up there).

**Comment by AWolf81** [comment]
@feinstaub Thanks, good point with the binaries in git history. I had to work with `filter-branch` to remove the large files. Like in this [blog post](https://torchbox.com/blog/how-remove-unwanted-files-your-git-repository/). Now the repo. size is OK with ~3MB.

**Pull request merged**
