### PR TITLE
Fix unicode encoding

### PR DESCRIPTION
**Pull request by AWolf81**
I think this is ready.

Please review and give me a feedback if anything is wrong.

**Changes**
- Fixed unicode encoding & added Chinese characters to test page
- Improved background scripts - used classes & cleaned code
- Added installation script for Linux & modified to Pyinstaller instead of Py2exe.
- Fixed Reveal on Open SUSE
- Added donation info to installed.html and readme.md
- Updated link to binary repo for Linux

**Todos after merging**
- Comment in bundle.sh script needs to be removed (Python is now bundled with Pyinstaller)
- Update CHANGELOG
- Test Ubuntu & Windows (re-test)
- Tag for release with version 0.99.57

### CODE REVIEW

**Comment by AWolf81** [comment]
I've quickly merged this with-out waiting for your feedback because I'd like to continue to work at the CHANGELOG in master.

If there are any problems we can fix them on master.

**Comment by feinstaub** [comment]
It's ok. If there are problems they can be fixed later.

The README.md can also be fine-tuned later. What I currently don't like that we have to spend 100 USD for a certificate. Why is it this so expensive? Does the high price makes our addon more secure? Who gets the money? This has a we-waste-money-for-nothing-but-to-remove-one-message-box smell.

**Comment by AWolf81** [comment]
The ~100 USD was from a quick search that I did. [google](https://www.google.de/search?q=code+signing+certificate+comodo&ie=utf-8&oe=utf-8&gws_rd=cr&dcr=0&ei=EfpRWu2SGIK3swGeiqzABg)
It seems that this is a yearly payment but more research is required because there are also supporter of open source that are cheaper.
I'm new to the code signing topic but I also don't like it. Paying for removing a blue box smells. Maybe we have to put a info somewhere that the user have to click on show more information to get the execute anyway option.

Good that you have created a issue for this. Thanks. I'll add a animated give there that's showing the dialog - to see initial dialog and after clicking show more.

Should we add an info to installed.html about this? We can also add the image there. I think that would help.

At the moment, I'm doing the Ubuntu check and it seems my old version of FF version 54 (currently installed in my VM ware) has a problem with the extension. Maybe there was a change in the webextension api but I also need to check the code.

Windows & OpenSUSE are working with current HEAD of master (both FF 57). Installation of native app is working as well. Native app version 0.1.1

**Comment by feinstaub** [comment]
> At the moment, I'm doing the Ubuntu check and it seems my old version of FF version 54 (currently installed in my VM ware) has a problem with the extension. Maybe there was a change in the webextension api but I also need to check the code.

If you don't find the problem I think it is ok to drop support for old FF versions

> Windows & OpenSUSE are working with current HEAD of master (both FF 57). Installation of native app is working as well. Native app version 0.1.1

Great.

**Comment by AWolf81** [comment]
@Feinstaub OK, please create the bundle and sign it. If there is a problem with signing please let me know and I'll try to help but it's difficult with-out credentials. In my opinion the extension is now ready for reviewing and publishing at Mozilla gallery.

I've also added the info to code signing warning to the post-install page. Tag 0.99.57 is created & changelog is up-to-date.

The problem with FF54 is fixed and it's also working in that version. Ubuntu 16.04.3 (64bit) with FF54 & FF57 is working.
There is just one warning (something like "object not xrayable") that I haven't fixed yet but it's only a warning and can be fixed later.

In the next version I'd like to check if removing the js map files from production build is possible because I think they're not required. But I think we can do that later - it will reduce the extracted size by around 2 MB. I've also seen that the animated gif in installed.html is pretty large (~1MB) but we can check this later as well.

**Comment by feinstaub** [comment]
Tried to sign (see latest master) but it did fail, see README.dev.md there. I tried it with your instructions here https://github.com/feinstaub/webextension_local_filesystem_links/issues/95#issuecomment-355782008 and did some variations. No success.

InvalidManifest: Could not read manifest.json file at /home/dev/src/firefox_addon_local_filesystem_links/feinstaub/web-ext-artifacts/local_filesystem_links-0.99.57.zip/manifest.json: Error: ENOTDIR: not a directory, open '/home/dev/src/firefox_addon_local_filesystem_links/feinstaub/web-ext-artifacts/local_filesystem_links-0.99.57.zip/manifest.json'

**Comment by AWolf81** [comment]
With the following command after `npm run build` it should work:
`web-ext sign --api-key=userkey --api-secret=... -s dist`
(with web-ext globally installed `npm i web-ext -g`)

For my credentials it is not working - server response: You do not own this addon. That's correct. But for you it should work. Can you please try again with added `-s dist` when running sign command in root of extension?

I think `npm` is not needed in package.json and it would be better to remove it as dependency.

Manifest in dist should be OK as `web-ext lint -s dist` isn't showing an error for the manifest. There are 20 warnings but that's probably no problem - as JQuery is showing simillar warnings (Function eval, eval and innerHTML can be harmful.)

**Pull request merged**
